const langData = {
    "zh-TW": {
        "site_name": "睿學社",
        "nav_about": "關於我們",
        "nav_constitution": "學會章程",
        "nav_download": "App下載",
        "nav_development": "近期發展",
        "nav_leaders": "瞻仰領導",
        "nav_positions": "重要職位",
        "nav_sponsorship": "入會條件",
        "nav_community": "加入社群",
        "hero_title": "歡迎來到睿學社",
        "hero_desc": "匯聚頂尖學府的智慧與創新，共創未來。",
        "about_title": "關於睿學社",
        "about_mission_title": "我們的使命",
        "about_mission_desc": "連接全球頂尖學府的精英人才，促進學術交流與合作，推動社會進步與創新。",
        "about_uni_title": "頂尖學府",
        "about_uni_desc": "我們匯聚來自世界一流大學的學生、研究員與教授，打造一個高質量的學術社群。",
        "about_innov_title": "創新驅動",
        "about_innov_desc": "鼓勵跨學科的思維碰撞，激發創新火花，共同應對全球性挑戰。",
        "const_title": "學會章程",
        "const_general_title": "總則",
        "const_general_desc": "本學會宗旨、組織架構及會員權利義務等基本規範。",
        "const_view_full": "查看完整章程",
        "const_mgmt_title": "管理辦法",
        "const_mgmt_desc": "涵蓋學會日常運營、活動策劃、財務管理等方面的詳細規定。",
        "const_acad_title": "學術規範",
        "const_acad_desc": "保障學術誠信，鼓勵開放研究，促進學術成果的交流與傳播。",
        "dl_title": "App下載",
        "dl_app_title": "睿學社官方App",
        "dl_app_desc": "隨時隨地掌握學會最新動態，參與線上線下活動。立即下載，開啟您的睿學社之旅。",
        "dl_qr_title": "掃描下載",
        "dl_qr_desc": "使用您的手機掃描二維碼，即可快速下載睿學社App。",
        "dev_title": "學會近期發展",
        "dev_1_title": "2026年學術年會圓滿落幕",
        "dev_1_desc": "匯聚全球頂尖學者，就人工智能、生物科技等前沿領域展開深入探討。",
        "dev_2_title": "第一屆會閣選舉",
        "dev_2_desc": "章魚哥當選内閣會長",
        "dev_3_title": "擴展國際合作夥伴",
        "dev_3_desc": "與多所國際知名大學簽署合作協議，深化學術交流與人才培養。",
        "leaders_title": "瞻仰領導",
        "lead_1_name": "特朗普",
        "lead_1_desc": "美利堅合衆國",
        "lead_2_name": "習近平",
        "lead_2_desc": "中華人民共和國",
        "lead_3_name": "金正恩",
        "lead_3_desc": "朝鮮民主主義人民共和國",
        "pos_title": "重要職位人員",
        "pos_1_name": "Mr. Solomon",
        "pos_1_title": "技術及資訊科技管理處處長（副部級）",
        "pos_1_desc": "澳門城市大學 工商管理學學士",
        "pos_2_name": "Mr. Philos",
        "pos_2_title": "學會及學會内閣副會長（正部級）",
        "pos_2_desc": "香港大學 法學政治學學士",
        "pos_3_name": "Dr. Sweet",
        "pos_3_title": "學會及學會内閣會長（副會級）",
        "pos_3_desc": "馬來西亞理科大學 體育科學博士",
        "pos_4_name": "章魚哥",
        "pos_4_title": "學會中央委員會主席（正會級）",
        "pos_4_desc": "南洋理工大學 商業與計算機工程學士",
        "pos_list": "學會政務職位人員名單",
        "cond_title": "入會條件",
        "cond_1": "取得或就讀本科及以上學歷",
        "cond_2": "滿3年技術工作經驗",
        "cond_3": "應屆優秀A-Level/IB/AP/SAT/GCSE/DSE/高考考生",
        "cond_4": "經七大部及五分處推薦",
        "cond_5": "及年滿17周歲&未滿17歲需監護人授權+且不得擔任幹事或參與限制性活動*",
        "cond_prio_title": "優先入會條件",
        "cond_prio_1": "QS/THE/USNews全球前100高校相關專業在讀或畢業生",
        "cond_prio_2": "中國教育部首批985工程高校或211工程&醫學、法學、計算機等學科*在讀或畢業",
        "cond_prio_3": "碩士研究生及以上學歷者",
        "comm_title": "加入我們的社群",
        "comm_desc": "與全球精英學者交流，獲取最新資訊，參與精彩活動。",
        "foot_about": "關於學會",
        "foot_about_1": "學會章程",
        "foot_about_2": "Constitution of Club",
        "foot_about_3": "學會組織架構",
        "foot_about_4": "學會成員學歷統計",
        "foot_about_5": "合作夥伴",
        "foot_res": "學術資源",
        "foot_res_1": "學術論文",
        "foot_res_2": "研究項目",
        "foot_res_3": "在線課程",
        "foot_res_4": "電子圖書館",
        "foot_serv": "會員服務",
        "foot_serv_1": "會員申請",
        "foot_serv_2": "會員權益",
        "foot_serv_3": "愛國教育",
        "foot_serv_4": "國家新聞",
        "foot_serv_5": "學會會員登入",
        "foot_cont": "聯絡我們",
        "foot_cont_1": "國安舉報",
        "foot_cont_2": "反詐騙及國安知識",
        "foot_cont_3": "瞻仰領導",
        "foot_copy": "© 2026 LEARNAHOLICS CLUB. All rights reserved. | 追求真理，崇尚學術",
        "modal_title": "請使用Discord",
        "modal_desc": "我們僅支持Discord加入社群，多謝配合",
        "modal_btn": "確認"
    },
    "zh-CN": {
        "site_name": "睿学社",
        "nav_about": "关于我们",
        "nav_constitution": "学会章程",
        "nav_download": "App下载",
        "nav_development": "近期发展",
        "nav_leaders": "瞻仰领导",
        "nav_positions": "重要职位",
        "nav_sponsorship": "入会条件",
        "nav_community": "加入社群",
        "hero_title": "欢迎来到睿学社",
        "hero_desc": "汇聚顶尖学府的智慧与创新，共创未来。",
        "about_title": "关于睿学社",
        "about_mission_title": "我们的使命",
        "about_mission_desc": "连接全球顶尖学府的精英人才，促进学术交流与合作，推动社会进步与创新。",
        "about_uni_title": "顶尖学府",
        "about_uni_desc": "我们汇聚来自世界一流大学的学生、研究员与教授，打造一个高质量的学术社群。",
        "about_innov_title": "创新驱动",
        "about_innov_desc": "鼓励跨学科的思维碰撞，激发创新火花，共同应对全球性挑战。",
        "const_title": "学会章程",
        "const_general_title": "总则",
        "const_general_desc": "本学会宗旨、组织架构及会员权利义务等基本规范。",
        "const_view_full": "查看完整章程",
        "const_mgmt_title": "管理办法",
        "const_mgmt_desc": "涵盖学会日常运营、活动策划、财务管理等方面的详细规定。",
        "const_acad_title": "学术规范",
        "const_acad_desc": "保障学术诚信，鼓励开放研究，促进学术成果的交流与传播。",
        "dl_title": "App下载",
        "dl_app_title": "睿学社官方App",
        "dl_app_desc": "随时随地掌握学会最新动态，参与线上线下活动。立即下载，开启您的睿学社之旅。",
        "dl_qr_title": "扫描下载",
        "dl_qr_desc": "使用您的手机扫描二维码，即可快速下载睿学社App。",
        "dev_title": "学会近期发展",
        "dev_1_title": "2026年学术年会圆满落幕",
        "dev_1_desc": "汇聚全球顶尖学者，就人工智能、生物科技等前沿领域展开深入探讨。",
        "dev_2_title": "第一届会阁选举",
        "dev_2_desc": "章鱼哥当选内阁会长",
        "dev_3_title": "扩展国际合作伙伴",
        "dev_3_desc": "与多所国际知名大学签署合作协议，深化学术交流与人才培养。",
        "leaders_title": "瞻仰领导",
        "lead_1_name": "特朗普",
        "lead_1_desc": "美利坚合众国",
        "lead_2_name": "习近平",
        "lead_2_desc": "中华人民共和国",
        "lead_3_name": "金正恩",
        "lead_3_desc": "朝鲜民主主义人民共和国",
        "pos_title": "重要职位人员",
        "pos_1_name": "Mr. Solomon",
        "pos_1_title": "技术及资讯科技管理处处长（副部级）",
        "pos_1_desc": "澳门城市大学 工商管理学学士",
        "pos_2_name": "Mr. Philos",
        "pos_2_title": "学会及学会内阁副会长（正部级）",
        "pos_2_desc": "香港大学 法学政治学学士",
        "pos_3_name": "Dr. Sweet",
        "pos_3_title": "学会及学会内阁会长（副会级）",
        "pos_3_desc": "马来西亚理科大学 体育科学博士",
        "pos_4_name": "章鱼哥",
        "pos_4_title": "学会中央委员会主席（正会级）",
        "pos_4_desc": "南洋理工大学 商业与计算机工程学士",
        "pos_list": "学会政务职位人员名单",
        "cond_title": "入会条件",
        "cond_1": "取得或就读本科及以上学历",
        "cond_2": "满3年技术工作经验",
        "cond_3": "应届优秀A-Level/IB/AP/SAT/GCSE/DSE/高考考生",
        "cond_4": "经七大部及五分处推荐",
        "cond_5": "及年满17周岁&未满17岁需监护人授权+且不得担任干事或参与限制性活动*",
        "cond_prio_title": "优先入会条件",
        "cond_prio_1": "QS/THE/USNews全球前100高校相关专业在读或毕业生",
        "cond_prio_2": "中国教育部首批985工程高校或211工程&医学、法学、计算机等学科*在读或毕业",
        "cond_prio_3": "硕士研究生及以上学历者",
        "comm_title": "加入我们的社群",
        "comm_desc": "与全球精英学者交流，获取最新资讯，参与精彩活动。",
        "foot_about": "关于学会",
        "foot_about_1": "学会章程",
        "foot_about_2": "Constitution of Club",
        "foot_about_3": "学会组织架构",
        "foot_about_4": "学会成员学历统计",
        "foot_about_5": "合作伙伴",
        "foot_res": "学术资源",
        "foot_res_1": "学术论文",
        "foot_res_2": "研究项目",
        "foot_res_3": "在线课程",
        "foot_res_4": "电子图书馆",
        "foot_serv": "会员服务",
        "foot_serv_1": "会员申请",
        "foot_serv_2": "会员权益",
        "foot_serv_3": "爱国教育",
        "foot_serv_4": "国家新闻",
        "foot_serv_5": "学会会员登入",
        "foot_cont": "联系我们",
        "foot_cont_1": "国安举报",
        "foot_cont_2": "反诈骗及国安知识",
        "foot_cont_3": "瞻仰领导",
        "foot_copy": "© 2026 LEARNAHOLICS CLUB. All rights reserved. | 追求真理，崇尚学术",
        "modal_title": "请使用Discord",
        "modal_desc": "我们仅支持Discord加入社群，多谢配合",
        "modal_btn": "确认"
    },
    "en": {
        "site_name": "Learnaholics Club",
        "nav_about": "About Us",
        "nav_constitution": "Constitution",
        "nav_download": "App Download",
        "nav_development": "Recent Devs",
        "nav_leaders": "Our Leaders",
        "nav_positions": "Key Roles",
        "nav_sponsorship": "Membership",
        "nav_community": "Community",
        "hero_title": "Welcome to Learnaholics Club",
        "hero_desc": "Gathering wisdom and innovation from top universities to create the future.",
        "about_title": "About Learnaholics Club",
        "about_mission_title": "Our Mission",
        "about_mission_desc": "Connecting elite talents globally to promote academic exchange and social innovation.",
        "about_uni_title": "Top Universities",
        "about_uni_desc": "We gather students and professors from world-class universities into a high-quality community.",
        "about_innov_title": "Innovation Driven",
        "about_innov_desc": "Encouraging interdisciplinary thinking to spark innovation and tackle global challenges.",
        "const_title": "Constitution",
        "const_general_title": "General Rules",
        "const_general_desc": "Basic norms covering the purpose, structure, and member rights.",
        "const_view_full": "View Full Constitution",
        "const_mgmt_title": "Management",
        "const_mgmt_desc": "Detailed rules on daily operations, activities, and financial management.",
        "const_acad_title": "Academic Norms",
        "const_acad_desc": "Ensuring academic integrity and promoting open research sharing.",
        "dl_title": "App Download",
        "dl_app_title": "Official App",
        "dl_app_desc": "Stay updated and join activities anywhere. Download now to start your journey.",
        "dl_qr_title": "Scan to Download",
        "dl_qr_desc": "Use your phone to scan the QR code and download the app instantly.",
        "dev_title": "Recent Developments",
        "dev_1_title": "2026 Academic Annual Conference",
        "dev_1_desc": "Global top scholars gathered to deeply discuss AI, biotech, and more.",
        "dev_2_title": "First Cabinet Election",
        "dev_2_desc": "Squidward elected as Cabinet President.",
        "dev_3_title": "Expanding Partnerships",
        "dev_3_desc": "Signed agreements with multiple global universities for academic exchange.",
        "leaders_title": "Our Leaders",
        "lead_1_name": "Donald Trump",
        "lead_1_desc": "United States of America",
        "lead_2_name": "Xi Jinping",
        "lead_2_desc": "People's Republic of China",
        "lead_3_name": "Kim Jong-un",
        "lead_3_desc": "Democratic People's Republic of Korea",
        "pos_title": "Key Personnel",
        "pos_1_name": "Mr. Solomon",
        "pos_1_title": "Director of Tech & IT (Vice-ministerial level)",
        "pos_1_desc": "City University of Macau - BBA",
        "pos_2_name": "Mr. Philos",
        "pos_2_title": "Vice President of the Club (Ministerial level)",
        "pos_2_desc": "The University of Hong Kong - LLB & Politics",
        "pos_3_name": "Dr. Sweet",
        "pos_3_title": "President of the Club (Vice-presidential level / Vice-chairperson level)",
        "pos_3_desc": "USM - PhD in Sports Science",
        "pos_4_name": "Squidward",
        "pos_4_title": "Chairman of Central Committee (Presidential level / Chairperson level)",
        "pos_4_desc": "NTU - B.Eng in Business and Computing",
        "pos_list": "List of Club Political Appointees",
        "cond_title": "Membership Criteria",
        "cond_1": "Hold or pursuing a Bachelor's degree or above",
        "cond_2": "At least 3 years of technical work experience",
        "cond_3": "Outstanding A-Level/IB/AP/SAT/GCSE/DSE candidates",
        "cond_4": "Recommended by 7 Major Depts and 5 Branches",
        "cond_5": "Aged 17+ (Minors need guardian consent) & Activity limits apply*",
        "cond_prio_title": "Priority Membership",
        "cond_prio_1": "Students/Alumni from Top 100 QS/THE/USNews Universities",
        "cond_prio_2": "Project 985/211 Universities in China (Med, Law, CS)*",
        "cond_prio_3": "Master's degree holders or above",
        "comm_title": "Join Our Community",
        "comm_desc": "Connect with elite scholars worldwide and join exciting events.",
        "foot_about": "About",
        "foot_about_1": "Constitution",
        "foot_about_2": "Constitution of Club",
        "foot_about_3": "Organizational Structure",
        "foot_about_4": "Member Education Stats",
        "foot_about_5": "Partners",
        "foot_res": "Resources",
        "foot_res_1": "Academic Papers",
        "foot_res_2": "Research Projects",
        "foot_res_3": "Online Courses",
        "foot_res_4": "E-Library",
        "foot_serv": "Services",
        "foot_serv_1": "Apply for Membership",
        "foot_serv_2": "Member Benefits",
        "foot_serv_3": "Patriotic Education",
        "foot_serv_4": "National News",
        "foot_serv_5": "Member Login",
        "foot_cont": "Contact Us",
        "foot_cont_1": "National Security Report",
        "foot_cont_2": "Anti-Fraud Knowledge",
        "foot_cont_3": "Admire Leaders",
        "foot_copy": "© 2026 LEARNAHOLICS CLUB. All rights reserved. | Truth & Academia",
        "modal_title": "Please use Discord",
        "modal_desc": "We only support Discord for our community. Thank you.",
        "modal_btn": "Confirm"
    },
    "ja": {
        "site_name": "睿学社",
        "nav_about": "私たちについて",
        "nav_constitution": "学会定款",
        "nav_download": "アプリ",
        "nav_development": "最近の動向",
        "nav_leaders": "指導者",
        "nav_positions": "重要役職",
        "nav_sponsorship": "入会条件",
        "nav_community": "コミュニティ",
        "hero_title": "睿学社へようこそ",
        "hero_desc": "トップ大学の知恵と革新を集め、未来を共創する。",
        "about_title": "睿学社について",
        "about_mission_title": "私たちの使命",
        "about_mission_desc": "世界中のトップ大学のエリート人材を結びつけ、学術交流を促進します。",
        "about_uni_title": "トップ大学",
        "about_uni_desc": "世界一流大学の学生や教授を集め、高品質な学術コミュニティを構築します。",
        "about_innov_title": "イノベーション主導",
        "about_innov_desc": "学際的な思考を奨励し、世界的な課題に共同で取り組みます。",
        "const_title": "学会定款",
        "const_general_title": "総則",
        "const_general_desc": "学会の目的、組織構造、会員の権利と義務などの基本規範。",
        "const_view_full": "完全な定款を見る",
        "const_mgmt_title": "管理規則",
        "const_mgmt_desc": "日常運営、イベント企画、財務管理に関する詳細な規定。",
        "const_acad_title": "学術規範",
        "const_acad_desc": "学術の誠実性を保証し、研究のオープンな交流を促進します。",
        "dl_title": "アプリのダウンロード",
        "dl_app_title": "公式アプリ",
        "dl_app_desc": "いつでも学会の最新情報を把握できます。今すぐダウンロードしてください。",
        "dl_qr_title": "スキャンしてダウンロード",
        "dl_qr_desc": "スマートフォンのカメラでQRコードをスキャンしてダウンロードできます。",
        "dev_title": "最近の発展",
        "dev_1_title": "2026年学術年次総会が成功裏に閉幕",
        "dev_1_desc": "世界のトップ学者が集まり、AIやバイオテクノロジーについて深く議論しました。",
        "dev_2_title": "第1回内閣選挙",
        "dev_2_desc": "イカルドが内閣会長に当選しました。",
        "dev_3_title": "国際パートナーの拡大",
        "dev_3_desc": "複数の著名な国際大学と協力協定を締結しました。",
        "leaders_title": "指導者を仰ぐ",
        "lead_1_name": "ドナルド・トランプ",
        "lead_1_desc": "アメリカ合衆国",
        "lead_2_name": "習近平",
        "lead_2_desc": "中華人民共和国",
        "lead_3_name": "金正恩",
        "lead_3_desc": "朝鮮民主主義人民共和国",
        "pos_title": "重要役職者",
        "pos_1_name": "Mr. Solomon",
        "pos_1_title": "技術情報管理局局長（副大臣級）",
        "pos_1_desc": "マカオ城市大学 経営学学士",
        "pos_2_name": "Mr. Philos",
        "pos_2_title": "学会および内閣副会長（大臣級）",
        "pos_2_desc": "香港大学 法学および政治学学士",
        "pos_3_name": "Dr. Sweet",
        "pos_3_title": "学会および内閣会長（副会長級）",
        "pos_3_desc": "マレーシアサインズ大学 スポーツ科学博士",
        "pos_4_name": "イカルド",
        "pos_4_title": "学会中央委員会主席（正会長級）",
        "pos_4_desc": "南洋理工大学 ビジネスとコンピューティング工学士",
        "pos_list": "学会政務役職者名簿",
        "cond_title": "入会条件",
        "cond_1": "学士号以上の学位を取得または在学中",
        "cond_2": "3年以上の技術業務経験",
        "cond_3": "優秀なA-Level/IB/AP/SATなどの受験生",
        "cond_4": "7つの主要部門および5つの支部の推薦",
        "cond_5": "17歳以上（未成年は保護者の同意が必要）",
        "cond_prio_title": "優先入会条件",
        "cond_prio_1": "QS/THE等世界トップ100大学の関連専攻",
        "cond_prio_2": "中国985/211大学の医学・法学・情報学など",
        "cond_prio_3": "修士号以上の学位保持者",
        "comm_title": "コミュニティに参加",
        "comm_desc": "世界のエリートと交流し、最新情報を手に入れましょう。",
        "foot_about": "学会について",
        "foot_about_1": "学会定款",
        "foot_about_2": "Constitution of Club",
        "foot_about_3": "組織構造",
        "foot_about_4": "会員の学歴統計",
        "foot_about_5": "パートナー",
        "foot_res": "学術リソース",
        "foot_res_1": "学術論文",
        "foot_res_2": "研究プロジェクト",
        "foot_res_3": "オンラインコース",
        "foot_res_4": "電子図書館",
        "foot_serv": "会員サービス",
        "foot_serv_1": "会員申請",
        "foot_serv_2": "会員特典",
        "foot_serv_3": "愛国教育",
        "foot_serv_4": "国家ニュース",
        "foot_serv_5": "会員ログイン",
        "foot_cont": "お問い合わせ",
        "foot_cont_1": "国家安全通報",
        "foot_cont_2": "詐欺防止知識",
        "foot_cont_3": "指導者を仰ぐ",
        "foot_copy": "© 2026 LEARNAHOLICS CLUB. All rights reserved. | 真理の追求",
        "modal_title": "Discordをご利用ください",
        "modal_desc": "コミュニティへの参加はDiscordのみ対応しております。",
        "modal_btn": "確認"
    },
    "ko": {
        "site_name": "예학사",
        "nav_about": "소개",
        "nav_constitution": "학회 정관",
        "nav_download": "앱 다운로드",
        "nav_development": "최근 동향",
        "nav_leaders": "지도자",
        "nav_positions": "주요 직위",
        "nav_sponsorship": "가입 조건",
        "nav_community": "커뮤니티",
        "hero_title": "예학사에 오신 것을 환영합니다",
        "hero_desc": "명문대의 지혜와 혁신을 모아 미래를 창조합니다.",
        "about_title": "예학사 소개",
        "about_mission_title": "우리의 사명",
        "about_mission_desc": "글로벌 명문대의 엘리트 인재를 연결하고 학술 교류를 촉진합니다.",
        "about_uni_title": "명문 대학교",
        "about_uni_desc": "세계 일류 대학의 학생과 교수를 모아 고품질 학술 커뮤니티를 구축합니다.",
        "about_innov_title": "혁신 주도",
        "about_innov_desc": "학제간 융합 사고를 장려하여 글로벌 과제에 대응합니다.",
        "const_title": "학회 정관",
        "const_general_title": "총칙",
        "const_general_desc": "학회의 목적, 조직 구조 및 회원의 권리와 의무.",
        "const_view_full": "전체 정관 보기",
        "const_mgmt_title": "관리 규정",
        "const_mgmt_desc": "일상 운영, 이벤트 기획 및 재무 관리에 대한 세부 규정.",
        "const_acad_title": "학술 규범",
        "const_acad_desc": "학문적 무결성을 보장하고 연구 교류를 촉진합니다.",
        "dl_title": "앱 다운로드",
        "dl_app_title": "공식 앱",
        "dl_app_desc": "언제 어디서나 최신 동향을 파악하세요. 지금 다운로드하세요.",
        "dl_qr_title": "스캔하여 다운로드",
        "dl_qr_desc": "스마트폰으로 QR 코드를 스캔하여 빠르게 다운로드하세요.",
        "dev_title": "최근 발전",
        "dev_1_title": "2026년 학술 연례 회의 성료",
        "dev_1_desc": "세계 최고의 학자들이 모여 AI 및 생명공학 등을 논의했습니다.",
        "dev_2_title": "제1대 내각 선거",
        "dev_2_desc": "징징이가 내각 회장으로 당선되었습니다.",
        "dev_3_title": "국제 파트너십 확장",
        "dev_3_desc": "다수의 국제 유명 대학과 협력 협정을 체결했습니다.",
        "leaders_title": "지도자 존경",
        "lead_1_name": "도널드 트럼프",
        "lead_1_desc": "미합중국",
        "lead_2_name": "시진핑",
        "lead_2_desc": "중화인민공화국",
        "lead_3_name": "김정은",
        "lead_3_desc": "조선민주주의인민공화국",
        "pos_title": "주요 직위 인원",
        "pos_1_name": "Mr. Solomon",
        "pos_1_title": "기술 및 IT 관리처장 (차관급)",
        "pos_1_desc": "마카오성시 대학 경영학 학사",
        "pos_2_name": "Mr. Philos",
        "pos_2_title": "학회 및 내각 부회장 (장관급)",
        "pos_2_desc": "홍콩 대학 법학 및 정치학 학사",
        "pos_3_name": "Dr. Sweet",
        "pos_3_title": "학회 및 내각 회장 (부회장급)",
        "pos_3_desc": "말레이시아 과학 대학 스포츠 과학 박사",
        "pos_4_name": "징징이",
        "pos_4_title": "학회 중앙위원회 위원장 (정회장급)",
        "pos_4_desc": "난양 이공대학 비즈니스 및 컴퓨터 공학 학사",
        "pos_list": "학회 정무직 인원 명단",
        "cond_title": "가입 조건",
        "cond_1": "학사 이상 학위 취득 또는 재학",
        "cond_2": "3년 이상 기술 업무 경력",
        "cond_3": "우수한 A-Level/IB 등 수험생",
        "cond_4": "7대 부서 및 5개 지부 추천",
        "cond_5": "만 17세 이상 (미성년자 보호자 동의 필요)",
        "cond_prio_title": "우선 가입 조건",
        "cond_prio_1": "QS/THE 등 글로벌 100대 대학 관련 전공",
        "cond_prio_2": "중국 985/211 대학의 의학, 법학, IT 등 전공",
        "cond_prio_3": "석사 이상 학위 소지자",
        "comm_title": "커뮤니티 가입",
        "comm_desc": "전 세계 엘리트 학자들과 교류하고 최신 정보를 얻으세요.",
        "foot_about": "학회 소개",
        "foot_about_1": "학회 정관",
        "foot_about_2": "Constitution of Club",
        "foot_about_3": "조직 구조",
        "foot_about_4": "회원 학력 통계",
        "foot_about_5": "파트너",
        "foot_res": "학술 리소스",
        "foot_res_1": "학술 논문",
        "foot_res_2": "연구 프로젝트",
        "foot_res_3": "온라인 코스",
        "foot_res_4": "전자 도서관",
        "foot_serv": "회원 서비스",
        "foot_serv_1": "회원 가입 신청",
        "foot_serv_2": "회원 혜택",
        "foot_serv_3": "애국 교육",
        "foot_serv_4": "국가 뉴스",
        "foot_serv_5": "회원 로그인",
        "foot_cont": "문의하기",
        "foot_cont_1": "국가 안보 신고",
        "foot_cont_2": "사기 방지 지식",
        "foot_cont_3": "지도자 존경",
        "foot_copy": "© 2026 LEARNAHOLICS CLUB. All rights reserved. | 진리 탐구",
        "modal_title": "Discord를 사용해주세요",
        "modal_desc": "커뮤니티 가입은 Discord만 지원합니다.",
        "modal_btn": "확인"
    },
    "fr": {
        "site_name": "Learnaholics Club",
        "nav_about": "À propos",
        "nav_constitution": "Constitution",
        "nav_download": "Télécharger l'App",
        "nav_development": "Développements Récents",
        "nav_leaders": "Nos Dirigeants",
        "nav_positions": "Rôles Clés",
        "nav_sponsorship": "Adhésion",
        "nav_community": "Communauté",
        "hero_title": "Bienvenue au Learnaholics Club",
        "hero_desc": "Rassembler la sagesse et l'innovation des meilleures universités pour créer l'avenir.",
        "about_title": "À propos du Learnaholics Club",
        "about_mission_title": "Notre Mission",
        "about_mission_desc": "Connecter les talents d'élite du monde entier pour promouvoir les échanges académiques et l'innovation sociale.",
        "about_uni_title": "Meilleures Universités",
        "about_uni_desc": "Nous rassemblons des étudiants et des professeurs d'universités de classe mondiale dans une communauté de haute qualité.",
        "about_innov_title": "Axé sur l'innovation",
        "about_innov_desc": "Encourager la réflexion interdisciplinaire pour susciter l'innovation et relever les défis mondiaux.",
        "const_title": "Constitution",
        "const_general_title": "Règles Générales",
        "const_general_desc": "Normes fondamentales couvrant l'objectif, la structure et les droits des membres.",
        "const_view_full": "Voir la Constitution Complète",
        "const_mgmt_title": "Gestion",
        "const_mgmt_desc": "Règles détaillées sur les opérations quotidiennes, les activités et la gestion financière.",
        "const_acad_title": "Normes Académiques",
        "const_acad_desc": "Garantir l'intégrité académique et promouvoir le partage de la recherche.",
        "dl_title": "Télécharger l'App",
        "dl_app_title": "Application Officielle",
        "dl_app_desc": "Restez informé et participez aux activités partout. Téléchargez maintenant.",
        "dl_qr_title": "Scanner pour Télécharger",
        "dl_qr_desc": "Utilisez votre téléphone pour scanner le code QR et télécharger l'application.",
        "dev_title": "Développements Récents",
        "dev_1_title": "Conférence Annuelle Académique 2026",
        "dev_1_desc": "Les meilleurs chercheurs mondiaux se sont réunis pour discuter d'IA, de biotechnologie, etc.",
        "dev_2_title": "Première Élection du Cabinet",
        "dev_2_desc": "Squidward élu Président du Cabinet.",
        "dev_3_title": "Expansion des Partenariats",
        "dev_3_desc": "Accords signés avec plusieurs universités mondiales pour des échanges académiques.",
        "leaders_title": "Nos Dirigeants",
        "lead_1_name": "Donald Trump",
        "lead_1_desc": "États-Unis d'Amérique",
        "lead_2_name": "Xi Jinping",
        "lead_2_desc": "République Populaire de Chine",
        "lead_3_name": "Kim Jong-un",
        "lead_3_desc": "République Populaire Démocratique de Corée",
        "pos_title": "Personnel Clé",
        "pos_1_name": "Mr. Solomon",
        "pos_1_title": "Directeur Technologie et Informatique (Niveau Vice-Ministre)",
        "pos_1_desc": "City University of Macau - BBA",
        "pos_2_name": "Mr. Philos",
        "pos_2_title": "Vice-Président du Club (Niveau Ministre)",
        "pos_2_desc": "The University of Hong Kong - LLB & Politique",
        "pos_3_name": "Dr. Sweet",
        "pos_3_title": "Président du Club (Niveau Vice-Présidentiel)",
        "pos_3_desc": "USM - Doctorat en Sciences du Sport",
        "pos_4_name": "Squidward",
        "pos_4_title": "Président du Comité Central (Niveau Présidentiel)",
        "pos_4_desc": "NTU - B.Eng en Affaires et Informatique",
        "pos_list": "Liste des Nominés Politiques du Club",
        "cond_title": "Critères d'Adhésion",
        "cond_1": "Détenir ou poursuivre un diplôme de licence ou supérieur",
        "cond_2": "Au moins 3 ans d'expérience technique",
        "cond_3": "Candidats exceptionnels A-Level/IB/AP/SAT/GCSE/DSE",
        "cond_4": "Recommandé par 7 Départements Majeurs et 5 Succursales",
        "cond_5": "Âgé de 17+ ans (Consentement parental pour les mineurs) & Limites d'activités applicables*",
        "cond_prio_title": "Adhésion Prioritaire",
        "cond_prio_1": "Étudiants/Anciens du Top 100 Universités QS/THE/USNews",
        "cond_prio_2": "Universités Projet 985/211 en Chine (Médecine, Droit, Informatique)*",
        "cond_prio_3": "Titulaires d'un Master ou supérieur",
        "comm_title": "Rejoignez Notre Communauté",
        "comm_desc": "Connectez-vous avec des chercheurs d'élite du monde entier et participez à des événements passionnants.",
        "foot_about": "À propos",
        "foot_about_1": "Constitution",
        "foot_about_2": "Constitution of Club",
        "foot_about_3": "Structure Organisationnelle",
        "foot_about_4": "Statistiques d'Éducation des Membres",
        "foot_about_5": "Partenaires",
        "foot_res": "Ressources",
        "foot_res_1": "Articles Académiques",
        "foot_res_2": "Projets de Recherche",
        "foot_res_3": "Cours en Ligne",
        "foot_res_4": "Bibliothèque Électronique",
        "foot_serv": "Services",
        "foot_serv_1": "Demande d'Adhésion",
        "foot_serv_2": "Avantages des Membres",
        "foot_serv_3": "Éducation Patriotique",
        "foot_serv_4": "Nouvelles Nationales",
        "foot_serv_5": "Connexion Membre",
        "foot_cont": "Contactez-Nous",
        "foot_cont_1": "Rapport Sécurité Nationale",
        "foot_cont_2": "Connaissances Anti-Fraude",
        "foot_cont_3": "Admirer les Dirigeants",
        "foot_copy": "© 2026 LEARNAHOLICS CLUB. Tous droits réservés. | Vérité et Monde Universitaire",
        "modal_title": "Utilisez Discord",
        "modal_desc": "Nous ne supportons que Discord pour notre communauté. Merci de votre compréhension.",
        "modal_btn": "Confirmer"
    },
    "es": {
        "site_name": "Learnaholics Club",
        "nav_about": "Sobre Nosotros",
        "nav_constitution": "Constitución",
        "nav_download": "Descargar App",
        "nav_development": "Desarrollos Recientes",
        "nav_leaders": "Nuestros Líderes",
        "nav_positions": "Roles Clave",
        "nav_sponsorship": "Membresía",
        "nav_community": "Comunidad",
        "hero_title": "Bienvenido a Learnaholics Club",
        "hero_desc": "Reuniendo sabiduría e innovación de las mejores universidades para crear el futuro.",
        "about_title": "Sobre Learnaholics Club",
        "about_mission_title": "Nuestra Misión",
        "about_mission_desc": "Conectar talentos de élite a nivel mundial para promover el intercambio académico y la innovación social.",
        "about_uni_title": "Mejores Universidades",
        "about_uni_desc": "Reunimos estudiantes y profesores de universidades de clase mundial en una comunidad de alta calidad.",
        "about_innov_title": "Impulsados por la Innovación",
        "about_innov_desc": "Fomentar el pensamiento interdisciplinario para despertar la innovación y abordar desafíos globales.",
        "const_title": "Constitución",
        "const_general_title": "Reglas Generales",
        "const_general_desc": "Normas básicas que cubren el propósito, la estructura y los derechos de los miembros.",
        "const_view_full": "Ver Constitución Completa",
        "const_mgmt_title": "Gestión",
        "const_mgmt_desc": "Reglas detalladas sobre operaciones diarias, actividades y gestión financiera.",
        "const_acad_title": "Normas Académicas",
        "const_acad_desc": "Garantizar la integridad académica y promover el intercambio abierto de investigaciones.",
        "dl_title": "Descargar App",
        "dl_app_title": "App Oficial",
        "dl_app_desc": "Mantente actualizado y únete a actividades en cualquier lugar. Descárgala ahora.",
        "dl_qr_title": "Escanear para Descargar",
        "dl_qr_desc": "Usa tu teléfono para escanear el código QR y descargar la aplicación al instante.",
        "dev_title": "Desarrollos Recientes",
        "dev_1_title": "Conferencia Anual Académica 2026",
        "dev_1_desc": "Los mejores académicos del mundo se reunieron para discutir sobre IA, biotecnología y más.",
        "dev_2_title": "Primera Elección del Gabinete",
        "dev_2_desc": "Squidward elegido Presidente del Gabinete.",
        "dev_3_title": "Expansión de Asociaciones",
        "dev_3_desc": "Acuerdos firmados con múltiples universidades globales para el intercambio académico.",
        "leaders_title": "Nuestros Líderes",
        "lead_1_name": "Donald Trump",
        "lead_1_desc": "Estados Unidos de América",
        "lead_2_name": "Xi Jinping",
        "lead_2_desc": "República Popular China",
        "lead_3_name": "Kim Jong-un",
        "lead_3_desc": "República Popular Democrática de Corea",
        "pos_title": "Personal Clave",
        "pos_1_name": "Mr. Solomon",
        "pos_1_title": "Director de Tecnología e Informática (Nivel Viceministerial)",
        "pos_1_desc": "City University of Macau - BBA",
        "pos_2_name": "Mr. Philos",
        "pos_2_title": "Vicepresidente del Club (Nivel Ministerial)",
        "pos_2_desc": "The University of Hong Kong - LLB y Política",
        "pos_3_name": "Dr. Sweet",
        "pos_3_title": "Presidente del Club (Nivel Vicepresidencial)",
        "pos_3_desc": "USM - Doctorado en Ciencias del Deporte",
        "pos_4_name": "Squidward",
        "pos_4_title": "Presidente del Comité Central (Nivel Presidencial)",
        "pos_4_desc": "NTU - B.Eng en Negocios y Computación",
        "pos_list": "Lista de Cargos Políticos del Club",
        "cond_title": "Criterios de Membresía",
        "cond_1": "Poseer o cursar una licenciatura o superior",
        "cond_2": "Al menos 3 años de experiencia en trabajo técnico",
        "cond_3": "Candidatos destacados de A-Level/IB/AP/SAT/GCSE/DSE",
        "cond_4": "Recomendado por 7 Departamentos Principales y 5 Sucursales",
        "cond_5": "Mayores de 17 años (menores necesitan consentimiento de tutor) y aplican límites de actividad*",
        "cond_prio_title": "Membresía Prioritaria",
        "cond_prio_1": "Estudiantes/Alumnos del Top 100 Universidades QS/THE/USNews",
        "cond_prio_2": "Universidades del Proyecto 985/211 en China (Medicina, Derecho, Informática)*",
        "cond_prio_3": "Titulares de un Máster o superior",
        "comm_title": "Únete a Nuestra Comunidad",
        "comm_desc": "Conéctate con académicos de élite de todo el mundo y únete a eventos emocionantes.",
        "foot_about": "Sobre Nosotros",
        "foot_about_1": "Constitución",
        "foot_about_2": "Constitution of Club",
        "foot_about_3": "Estructura Organizacional",
        "foot_about_4": "Estadísticas Educativas de Miembros",
        "foot_about_5": "Socios",
        "foot_res": "Recursos",
        "foot_res_1": "Documentos Académicos",
        "foot_res_2": "Proyectos de Investigación",
        "foot_res_3": "Cursos en Línea",
        "foot_res_4": "Biblioteca Electrónica",
        "foot_serv": "Servicios",
        "foot_serv_1": "Solicitar Membresía",
        "foot_serv_2": "Beneficios para Miembros",
        "foot_serv_3": "Educación Patriótica",
        "foot_serv_4": "Noticias Nacionales",
        "foot_serv_5": "Inicio de Sesión de Miembro",
        "foot_cont": "Contáctanos",
        "foot_cont_1": "Reporte de Seguridad Nacional",
        "foot_cont_2": "Conocimiento Antifraude",
        "foot_cont_3": "Admirar a los Líderes",
        "foot_copy": "© 2026 LEARNAHOLICS CLUB. Todos los derechos reservados. | Verdad y Academia",
        "modal_title": "Por favor usa Discord",
        "modal_desc": "Solo admitimos Discord para nuestra comunidad. Gracias por cooperar.",
        "modal_btn": "Confirmar"
    },
    "de": {
        "site_name": "Learnaholics Club",
        "nav_about": "Über Uns",
        "nav_constitution": "Satzung",
        "nav_download": "App Herunterladen",
        "nav_development": "Aktuelle Entwicklungen",
        "nav_leaders": "Unsere Leiter",
        "nav_positions": "Schlüsselrollen",
        "nav_sponsorship": "Mitgliedschaft",
        "nav_community": "Gemeinschaft",
        "hero_title": "Willkommen im Learnaholics Club",
        "hero_desc": "Wir sammeln Weisheit und Innovation von Spitzenuniversitäten, um die Zukunft zu gestalten.",
        "about_title": "Über Learnaholics Club",
        "about_mission_title": "Unsere Mission",
        "about_mission_desc": "Wir verbinden weltweit Elitetalente, um den akademischen Austausch und soziale Innovationen zu fördern.",
        "about_uni_title": "Spitzenuniversitäten",
        "about_uni_desc": "Wir versammeln Studenten und Professoren von Weltklasse-Universitäten zu einer hochwertigen Gemeinschaft.",
        "about_innov_title": "Innovationsgetrieben",
        "about_innov_desc": "Förderung interdisziplinären Denkens, um Innovationen anzustoßen und globale Herausforderungen zu meistern.",
        "const_title": "Satzung",
        "const_general_title": "Allgemeine Regeln",
        "const_general_desc": "Grundnormen, die Zweck, Struktur und Mitgliederrechte abdecken.",
        "const_view_full": "Vollständige Satzung Anzeigen",
        "const_mgmt_title": "Management",
        "const_mgmt_desc": "Detaillierte Regeln zum Tagesgeschäft, zu Aktivitäten und zur Finanzverwaltung.",
        "const_acad_title": "Akademische Normen",
        "const_acad_desc": "Gewährleistung der akademischen Integrität und Förderung des offenen Forschungsaustauschs.",
        "dl_title": "App Herunterladen",
        "dl_app_title": "Offizielle App",
        "dl_app_desc": "Bleiben Sie auf dem Laufenden und nehmen Sie überall an Aktivitäten teil. Jetzt herunterladen.",
        "dl_qr_title": "Zum Herunterladen Scannen",
        "dl_qr_desc": "Verwenden Sie Ihr Telefon, um den QR-Code zu scannen und die App sofort herunterzuladen.",
        "dev_title": "Aktuelle Entwicklungen",
        "dev_1_title": "Akademische Jahreskonferenz 2026",
        "dev_1_desc": "Weltweite Spitzenwissenschaftler versammelten sich, um KI, Biotechnologie und mehr eingehend zu diskutieren.",
        "dev_2_title": "Erste Kabinettswahl",
        "dev_2_desc": "Squidward zum Kabinettspräsidenten gewählt.",
        "dev_3_title": "Erweiterung der Partnerschaften",
        "dev_3_desc": "Vereinbarungen mit mehreren globalen Universitäten zum akademischen Austausch unterzeichnet.",
        "leaders_title": "Unsere Leiter",
        "lead_1_name": "Donald Trump",
        "lead_1_desc": "Vereinigte Staaten von Amerika",
        "lead_2_name": "Xi Jinping",
        "lead_2_desc": "Volksrepublik China",
        "lead_3_name": "Kim Jong-un",
        "lead_3_desc": "Demokratische Volksrepublik Korea",
        "pos_title": "Schlüsselpersonal",
        "pos_1_name": "Mr. Solomon",
        "pos_1_title": "Direktor für Technologie & IT (Vize-Ministerrang)",
        "pos_1_desc": "City University of Macau - BBA",
        "pos_2_name": "Mr. Philos",
        "pos_2_title": "Vizepräsident des Clubs (Ministerrang)",
        "pos_2_desc": "The University of Hong Kong - LLB & Politik",
        "pos_3_name": "Dr. Sweet",
        "pos_3_title": "Präsident des Clubs (Vize-Präsidentschaftsrang)",
        "pos_3_desc": "USM - Doktorat in Sportwissenschaften",
        "pos_4_name": "Squidward",
        "pos_4_title": "Vorsitzender des Zentralkomitees (Präsidentschaftsrang)",
        "pos_4_desc": "NTU - B.Eng in Wirtschaft und Informatik",
        "pos_list": "Liste der politischen Mandatsträger des Clubs",
        "cond_title": "Aufnahmekriterien",
        "cond_1": "Inhaber eines Bachelor-Abschlusses (oder höher) oder im Studium",
        "cond_2": "Mindestens 3 Jahre technische Berufserfahrung",
        "cond_3": "Hervorragende A-Level/IB/AP/SAT/GCSE/DSE-Kandidaten",
        "cond_4": "Empfohlen von 7 Hauptabteilungen und 5 Niederlassungen",
        "cond_5": "Ab 17 Jahren (Minderjährige benötigen die Zustimmung eines Erziehungsberechtigten) & Aktivitätseinschränkungen gelten*",
        "cond_prio_title": "Bevorzugte Mitgliedschaft",
        "cond_prio_1": "Studenten/Alumni der Top 100 QS/THE/USNews-Universitäten",
        "cond_prio_2": "Universitäten des Projekts 985/211 in China (Medizin, Jura, Informatik)*",
        "cond_prio_3": "Inhaber eines Master-Abschlusses oder höher",
        "comm_title": "Treten Sie Unserer Gemeinschaft Bei",
        "comm_desc": "Vernetzen Sie sich weltweit mit Elite-Wissenschaftlern und nehmen Sie an spannenden Events teil.",
        "foot_about": "Über Uns",
        "foot_about_1": "Satzung",
        "foot_about_2": "Constitution of Club",
        "foot_about_3": "Organisationsstruktur",
        "foot_about_4": "Bildungsstatistik der Mitglieder",
        "foot_about_5": "Partner",
        "foot_res": "Ressourcen",
        "foot_res_1": "Wissenschaftliche Arbeiten",
        "foot_res_2": "Forschungsprojekte",
        "foot_res_3": "Online-Kurse",
        "foot_res_4": "E-Bibliothek",
        "foot_serv": "Dienstleistungen",
        "foot_serv_1": "Mitgliedschaft Beantragen",
        "foot_serv_2": "Vorteile für Mitglieder",
        "foot_serv_3": "Patriotische Erziehung",
        "foot_serv_4": "Nationale Nachrichten",
        "foot_serv_5": "Mitglieder-Login",
        "foot_cont": "Kontakt",
        "foot_cont_1": "Nationale Sicherheit Melden",
        "foot_cont_2": "Anti-Betrugs-Wissen",
        "foot_cont_3": "Leiter Bewundern",
        "foot_copy": "© 2026 LEARNAHOLICS CLUB. Alle Rechte vorbehalten. | Wahrheit & Wissenschaft",
        "modal_title": "Bitte Discord nutzen",
        "modal_desc": "Wir unterstützen für unsere Community ausschließlich Discord. Vielen Dank für Ihr Verständnis.",
        "modal_btn": "Bestätigen"
    }
};
